services:
  wiki:
    build:
      context: .
      dockerfile: Dockerfile.prod
    extends:
      service: wiki
      file: docker-compose.yml
    environment:
      - MV_ENV=prod
      - GCS_BUCKET_NAME=gb_wiki_mw
      - GCS_HMAC_ACCESS_KEY=${GCS_HMAC_ACCESS_KEY}
      - GCS_HMAC_SECRET=${GCS_HMAC_SECRET}
